import { Product } from "../src/product";

export class ExpectedProduct extends Product {
    day: number;

    constructor(day:number, name: string, sellIn: number, price: number) {
        super(name, sellIn, price);
        this.day = day;
    }
}

export const expectedProducts:ExpectedProduct[] = [
    new ExpectedProduct(0, 'Medium Coverage', 10, 20),
    new ExpectedProduct(0, 'Full Coverage', 2, 0),
    new ExpectedProduct(0, 'Low Coverage', 5, 7),
    new ExpectedProduct(0, 'Mega Coverage', 0, 80),
    new ExpectedProduct(0, 'Mega Coverage', -1, 80),
    new ExpectedProduct(0, 'Special Full Coverage', 15, 20),
    new ExpectedProduct(0, 'Special Full Coverage', 10, 49),
    new ExpectedProduct(0, 'Special Full Coverage', 5, 49),
    new ExpectedProduct(0, 'Super Sale', 3, 6),

    new ExpectedProduct(1, 'Medium Coverage', 9, 19),
    new ExpectedProduct(1, 'Full Coverage', 1, 1),
    new ExpectedProduct(1, 'Low Coverage', 4, 6),
    new ExpectedProduct(1, 'Mega Coverage', 0, 80),
    new ExpectedProduct(1, 'Mega Coverage', -1, 80),
    new ExpectedProduct(1, 'Special Full Coverage', 14, 21),
    new ExpectedProduct(1, 'Special Full Coverage', 9, 50),
    new ExpectedProduct(1, 'Special Full Coverage', 4, 50),
    new ExpectedProduct(1, 'Super Sale', 2, 5),

    new ExpectedProduct(2, 'Medium Coverage', 8, 18),
    new ExpectedProduct(2, 'Full Coverage', 0, 2),
    new ExpectedProduct(2, 'Low Coverage', 3, 5),
    new ExpectedProduct(2, 'Mega Coverage', 0, 80),
    new ExpectedProduct(2, 'Mega Coverage', -1, 80),
    new ExpectedProduct(2, 'Special Full Coverage', 13, 22),
    new ExpectedProduct(2, 'Special Full Coverage', 8, 50),
    new ExpectedProduct(2, 'Special Full Coverage', 3, 50),
    new ExpectedProduct(2, 'Super Sale', 1, 4, ),

    new ExpectedProduct(3, 'Medium Coverage', 7, 17),
    new ExpectedProduct(3, 'Full Coverage', -1, 4),
    new ExpectedProduct(3, 'Low Coverage', 2, 4),
    new ExpectedProduct(3, 'Mega Coverage', 0, 80),
    new ExpectedProduct(3, 'Mega Coverage', -1, 80),
    new ExpectedProduct(3, 'Special Full Coverage', 12, 23),
    new ExpectedProduct(3, 'Special Full Coverage', 7, 50),
    new ExpectedProduct(3, 'Special Full Coverage', 2, 50),
    new ExpectedProduct(3, 'Super Sale', 0, 3),

    new ExpectedProduct(4, 'Medium Coverage', 6, 16),
    new ExpectedProduct(4, 'Full Coverage', -2, 6),
    new ExpectedProduct(4, 'Low Coverage', 1, 3),
    new ExpectedProduct(4, 'Mega Coverage', 0, 80),
    new ExpectedProduct(4, 'Mega Coverage', -1, 80),
    new ExpectedProduct(4, 'Special Full Coverage', 11, 24),
    new ExpectedProduct(4, 'Special Full Coverage', 6, 50),
    new ExpectedProduct(4, 'Special Full Coverage', 1, 50),
    new ExpectedProduct(4, 'Super Sale', -1, 1),

    new ExpectedProduct(5, 'Medium Coverage', 5, 15),
    new ExpectedProduct(5, 'Full Coverage', -3, 8),
    new ExpectedProduct(5, 'Low Coverage', 0, 2),
    new ExpectedProduct(5, 'Mega Coverage', 0, 80),
    new ExpectedProduct(5, 'Mega Coverage', -1, 80),
    new ExpectedProduct(5, 'Special Full Coverage', 10, 25),
    new ExpectedProduct(5, 'Special Full Coverage', 5, 50),
    new ExpectedProduct(5, 'Special Full Coverage', 0, 50),
    new ExpectedProduct(5, 'Super Sale', -2, 0),

    new ExpectedProduct(6, 'Medium Coverage', 4, 14),
    new ExpectedProduct(6, 'Full Coverage', -4, 10),
    new ExpectedProduct(6, 'Low Coverage', -1, 0),
    new ExpectedProduct(6, 'Mega Coverage', 0, 80),
    new ExpectedProduct(6, 'Mega Coverage', -1, 80),
    new ExpectedProduct(6, 'Special Full Coverage', 9, 27),
    new ExpectedProduct(6, 'Special Full Coverage', 4, 50),
    new ExpectedProduct(6, 'Special Full Coverage', -1, 0),
    new ExpectedProduct(6, 'Super Sale', -3, 0),

    new ExpectedProduct(7, 'Medium Coverage', 3, 13),
    new ExpectedProduct(7, 'Full Coverage', -5, 12),
    new ExpectedProduct(7, 'Low Coverage', -2, 0),
    new ExpectedProduct(7, 'Mega Coverage', 0, 80),
    new ExpectedProduct(7, 'Mega Coverage', -1, 80),
    new ExpectedProduct(7, 'Special Full Coverage', 8, 29),
    new ExpectedProduct(7, 'Special Full Coverage', 3, 50),
    new ExpectedProduct(7, 'Special Full Coverage', -2, 0),
    new ExpectedProduct(7, 'Super Sale', -4, 0),

    new ExpectedProduct(8, 'Medium Coverage', 2, 12),
    new ExpectedProduct(8, 'Full Coverage', -6, 14),
    new ExpectedProduct(8, 'Low Coverage', -3, 0),
    new ExpectedProduct(8, 'Mega Coverage', 0, 80),
    new ExpectedProduct(8, 'Mega Coverage', -1, 80),
    new ExpectedProduct(8, 'Special Full Coverage', 7, 31),
    new ExpectedProduct(8, 'Special Full Coverage', 2, 50),
    new ExpectedProduct(8, 'Special Full Coverage', -3, 0),
    new ExpectedProduct(8, 'Super Sale', -5, 0),

    new ExpectedProduct(9, 'Medium Coverage', 1, 11),
    new ExpectedProduct(9, 'Full Coverage', -7, 16),
    new ExpectedProduct(9, 'Low Coverage', -4, 0),
    new ExpectedProduct(9, 'Mega Coverage', 0, 80),
    new ExpectedProduct(9, 'Mega Coverage', -1, 80),
    new ExpectedProduct(9, 'Special Full Coverage', 6, 33),
    new ExpectedProduct(9, 'Special Full Coverage', 1, 50),
    new ExpectedProduct(9, 'Special Full Coverage', -4, 0),
    new ExpectedProduct(9, 'Super Sale', -6, 0),

    new ExpectedProduct(10, 'Medium Coverage', 0, 10),
    new ExpectedProduct(10, 'Full Coverage', -8, 18),
    new ExpectedProduct(10, 'Low Coverage', -5, 0),
    new ExpectedProduct(10, 'Mega Coverage', 0, 80),
    new ExpectedProduct(10, 'Mega Coverage', -1, 80),
    new ExpectedProduct(10, 'Special Full Coverage', 5, 35),
    new ExpectedProduct(10, 'Special Full Coverage', 0, 50),
    new ExpectedProduct(10, 'Special Full Coverage', -5, 0),
    new ExpectedProduct(10, 'Super Sale', -7, 0),

    new ExpectedProduct(11, 'Medium Coverage', -1, 8),
    new ExpectedProduct(11, 'Full Coverage', -9, 20),
    new ExpectedProduct(11, 'Low Coverage', -6, 0),
    new ExpectedProduct(11, 'Mega Coverage', 0, 80),
    new ExpectedProduct(11, 'Mega Coverage', -1, 80),
    new ExpectedProduct(11, 'Special Full Coverage', 4, 38),
    new ExpectedProduct(11, 'Special Full Coverage', -1, 0),
    new ExpectedProduct(11, 'Special Full Coverage', -6, 0),
    new ExpectedProduct(11, 'Super Sale', -8, 0),

    new ExpectedProduct(12, 'Medium Coverage', -2, 6),
    new ExpectedProduct(12, 'Full Coverage', -10, 22),
    new ExpectedProduct(12, 'Low Coverage', -7, 0),
    new ExpectedProduct(12, 'Mega Coverage', 0, 80),
    new ExpectedProduct(12, 'Mega Coverage', -1, 80),
    new ExpectedProduct(12, 'Special Full Coverage', 3, 41),
    new ExpectedProduct(12, 'Special Full Coverage', -2, 0),
    new ExpectedProduct(12, 'Special Full Coverage', -7, 0),
    new ExpectedProduct(12, 'Super Sale', -9, 0),

    new ExpectedProduct(13, 'Medium Coverage', -3, 4),
    new ExpectedProduct(13, 'Full Coverage', -11, 24),
    new ExpectedProduct(13, 'Low Coverage', -8, 0),
    new ExpectedProduct(13, 'Mega Coverage', 0, 80),
    new ExpectedProduct(13, 'Mega Coverage', -1, 80),
    new ExpectedProduct(13, 'Special Full Coverage', 2, 44),
    new ExpectedProduct(13, 'Special Full Coverage', -3, 0),
    new ExpectedProduct(13, 'Special Full Coverage', -8, 0),
    new ExpectedProduct(13, 'Super Sale', -10, 0),

    new ExpectedProduct(14, 'Medium Coverage', -4, 2),
    new ExpectedProduct(14, 'Full Coverage', -12, 26),
    new ExpectedProduct(14, 'Low Coverage', -9, 0),
    new ExpectedProduct(14, 'Mega Coverage', 0, 80),
    new ExpectedProduct(14, 'Mega Coverage', -1, 80),
    new ExpectedProduct(14, 'Special Full Coverage', 1, 47),
    new ExpectedProduct(14, 'Special Full Coverage', -4, 0),
    new ExpectedProduct(14, 'Special Full Coverage', -9, 0),
    new ExpectedProduct(14, 'Super Sale', -11, 0),

    new ExpectedProduct(15, 'Medium Coverage', -5, 0),
    new ExpectedProduct(15, 'Full Coverage', -13, 28),
    new ExpectedProduct(15, 'Low Coverage', -10, 0),
    new ExpectedProduct(15, 'Mega Coverage', 0, 80),
    new ExpectedProduct(15, 'Mega Coverage', -1, 80),
    new ExpectedProduct(15, 'Special Full Coverage', 0, 50),
    new ExpectedProduct(15, 'Special Full Coverage', -5, 0),
    new ExpectedProduct(15, 'Special Full Coverage', -10, 0),
    new ExpectedProduct(15, 'Super Sale', -12, 0),

    new ExpectedProduct(16, 'Medium Coverage', -6, 0),
    new ExpectedProduct(16, 'Full Coverage', -14, 30),
    new ExpectedProduct(16, 'Low Coverage', -11, 0),
    new ExpectedProduct(16, 'Mega Coverage', 0, 80),
    new ExpectedProduct(16, 'Mega Coverage', -1, 80),
    new ExpectedProduct(16, 'Special Full Coverage', -1, 0),
    new ExpectedProduct(16, 'Special Full Coverage', -6, 0),
    new ExpectedProduct(16, 'Special Full Coverage', -11, 0),
    new ExpectedProduct(16, 'Super Sale', -13, 0),

    new ExpectedProduct(17, 'Medium Coverage', -7, 0),
    new ExpectedProduct(17, 'Full Coverage', -15, 32),
    new ExpectedProduct(17, 'Low Coverage', -12, 0),
    new ExpectedProduct(17, 'Mega Coverage', 0, 80),
    new ExpectedProduct(17, 'Mega Coverage', -1, 80),
    new ExpectedProduct(17, 'Special Full Coverage', -2, 0),
    new ExpectedProduct(17, 'Special Full Coverage', -7, 0),
    new ExpectedProduct(17, 'Special Full Coverage', -12, 0),
    new ExpectedProduct(17, 'Super Sale', -14, 0),

    new ExpectedProduct(18, 'Medium Coverage', -8, 0),
    new ExpectedProduct(18, 'Full Coverage', -16, 34),
    new ExpectedProduct(18, 'Low Coverage', -13, 0),
    new ExpectedProduct(18, 'Mega Coverage', 0, 80),
    new ExpectedProduct(18, 'Mega Coverage', -1, 80),
    new ExpectedProduct(18, 'Special Full Coverage', -3, 0),
    new ExpectedProduct(18, 'Special Full Coverage', -8, 0),
    new ExpectedProduct(18, 'Special Full Coverage', -13, 0),
    new ExpectedProduct(18, 'Super Sale', -15, 0),

    new ExpectedProduct(19, 'Medium Coverage', -9, 0),
    new ExpectedProduct(19, 'Full Coverage', -17, 36),
    new ExpectedProduct(19, 'Low Coverage', -14, 0),
    new ExpectedProduct(19, 'Mega Coverage', 0, 80),
    new ExpectedProduct(19, 'Mega Coverage', -1, 80),
    new ExpectedProduct(19, 'Special Full Coverage', -4, 0),
    new ExpectedProduct(19, 'Special Full Coverage', -9, 0),
    new ExpectedProduct(19, 'Special Full Coverage', -14, 0),
    new ExpectedProduct(19, 'Super Sale', -16, 0),

    new ExpectedProduct(20, 'Medium Coverage', -10, 0),
    new ExpectedProduct(20, 'Full Coverage', -18, 38),
    new ExpectedProduct(20, 'Low Coverage', -15, 0),
    new ExpectedProduct(20, 'Mega Coverage', 0, 80),
    new ExpectedProduct(20, 'Mega Coverage', -1, 80),
    new ExpectedProduct(20, 'Special Full Coverage', -5, 0),
    new ExpectedProduct(20, 'Special Full Coverage', -10, 0),
    new ExpectedProduct(20, 'Special Full Coverage', -15, 0),
    new ExpectedProduct(20, 'Super Sale', -17, 0),

    new ExpectedProduct(21, 'Medium Coverage', -11, 0),
    new ExpectedProduct(21, 'Full Coverage', -19, 40),
    new ExpectedProduct(21, 'Low Coverage', -16, 0),
    new ExpectedProduct(21, 'Mega Coverage', 0, 80),
    new ExpectedProduct(21, 'Mega Coverage', -1, 80),
    new ExpectedProduct(21, 'Special Full Coverage', -6, 0),
    new ExpectedProduct(21, 'Special Full Coverage', -11, 0),
    new ExpectedProduct(21, 'Special Full Coverage', -16, 0),
    new ExpectedProduct(21, 'Super Sale', -18, 0),

    new ExpectedProduct(22, 'Medium Coverage', -12, 0),
    new ExpectedProduct(22, 'Full Coverage', -20, 42),
    new ExpectedProduct(22, 'Low Coverage', -17, 0),
    new ExpectedProduct(22, 'Mega Coverage', 0, 80),
    new ExpectedProduct(22, 'Mega Coverage', -1, 80),
    new ExpectedProduct(22, 'Special Full Coverage', -7, 0),
    new ExpectedProduct(22, 'Special Full Coverage', -12, 0),
    new ExpectedProduct(22, 'Special Full Coverage', -17, 0),
    new ExpectedProduct(22, 'Super Sale', -19, 0),

    new ExpectedProduct(23, 'Medium Coverage', -13, 0),
    new ExpectedProduct(23, 'Full Coverage', -21, 44),
    new ExpectedProduct(23, 'Low Coverage', -18, 0),
    new ExpectedProduct(23, 'Mega Coverage', 0, 80),
    new ExpectedProduct(23, 'Mega Coverage', -1, 80),
    new ExpectedProduct(23, 'Special Full Coverage', -8, 0),
    new ExpectedProduct(23, 'Special Full Coverage', -13, 0),
    new ExpectedProduct(23, 'Special Full Coverage', -18, 0),
    new ExpectedProduct(23, 'Super Sale', -20, 0),

    new ExpectedProduct(24, 'Medium Coverage', -14, 0),
    new ExpectedProduct(24, 'Full Coverage', -22, 46),
    new ExpectedProduct(24, 'Low Coverage', -19, 0),
    new ExpectedProduct(24, 'Mega Coverage', 0, 80),
    new ExpectedProduct(24, 'Mega Coverage', -1, 80),
    new ExpectedProduct(24, 'Special Full Coverage', -9, 0),
    new ExpectedProduct(24, 'Special Full Coverage', -14, 0),
    new ExpectedProduct(24, 'Special Full Coverage', -19, 0),
    new ExpectedProduct(24, 'Super Sale', -21, 0),

    new ExpectedProduct(25, 'Medium Coverage', -15, 0),
    new ExpectedProduct(25, 'Full Coverage', -23, 48),
    new ExpectedProduct(25, 'Low Coverage', -20, 0),
    new ExpectedProduct(25, 'Mega Coverage', 0, 80),
    new ExpectedProduct(25, 'Mega Coverage', -1, 80),
    new ExpectedProduct(25, 'Special Full Coverage', -10, 0),
    new ExpectedProduct(25, 'Special Full Coverage', -15, 0),
    new ExpectedProduct(25, 'Special Full Coverage', -20, 0),
    new ExpectedProduct(25, 'Super Sale', -22, 0),

    new ExpectedProduct(26, 'Medium Coverage', -16, 0),
    new ExpectedProduct(26, 'Full Coverage', -24, 50),
    new ExpectedProduct(26, 'Low Coverage', -21, 0),
    new ExpectedProduct(26, 'Mega Coverage', 0, 80),
    new ExpectedProduct(26, 'Mega Coverage', -1, 80),
    new ExpectedProduct(26, 'Special Full Coverage', -11, 0),
    new ExpectedProduct(26, 'Special Full Coverage', -16, 0),
    new ExpectedProduct(26, 'Special Full Coverage', -21, 0),
    new ExpectedProduct(26, 'Super Sale', -23, 0),

    new ExpectedProduct(27, 'Medium Coverage', -17, 0),
    new ExpectedProduct(27, 'Full Coverage', -25, 50),
    new ExpectedProduct(27, 'Low Coverage', -22, 0),
    new ExpectedProduct(27, 'Mega Coverage', 0, 80),
    new ExpectedProduct(27, 'Mega Coverage', -1, 80),
    new ExpectedProduct(27, 'Special Full Coverage', -12, 0),
    new ExpectedProduct(27, 'Special Full Coverage', -17, 0),
    new ExpectedProduct(27, 'Special Full Coverage', -22, 0),
    new ExpectedProduct(27, 'Super Sale', -24, 0),

    new ExpectedProduct(28,'Medium Coverage', -18, 0),
    new ExpectedProduct(28,'Full Coverage', -26, 50),
    new ExpectedProduct(28,'Low Coverage', -23, 0),
    new ExpectedProduct(28,'Mega Coverage', 0, 80),
    new ExpectedProduct(28,'Mega Coverage', -1, 80),
    new ExpectedProduct(28,'Special Full Coverage', -13, 0),
    new ExpectedProduct(28,'Special Full Coverage', -18, 0),
    new ExpectedProduct(28,'Special Full Coverage', -23, 0),
    new ExpectedProduct(28,'Super Sale', -25, 0),

    new ExpectedProduct(29, 'Medium Coverage', -19, 0),
    new ExpectedProduct(29, 'Full Coverage', -27, 50),
    new ExpectedProduct(29, 'Low Coverage', -24, 0),
    new ExpectedProduct(29, 'Mega Coverage', 0, 80),
    new ExpectedProduct(29, 'Mega Coverage', -1, 80),
    new ExpectedProduct(29, 'Special Full Coverage', -14, 0),
    new ExpectedProduct(29, 'Special Full Coverage', -19, 0),
    new ExpectedProduct(29, 'Special Full Coverage', -24, 0),
    new ExpectedProduct(29, 'Super Sale', -26, 0),

    new ExpectedProduct(30, 'Medium Coverage', -20, 0),
    new ExpectedProduct(30, 'Full Coverage', -28, 50),
    new ExpectedProduct(30, 'Low Coverage', -25, 0),
    new ExpectedProduct(30, 'Mega Coverage', 0, 80),
    new ExpectedProduct(30, 'Mega Coverage', -1, 80),
    new ExpectedProduct(30, 'Special Full Coverage', -15, 0),
    new ExpectedProduct(30, 'Special Full Coverage', -20, 0),
    new ExpectedProduct(30, 'Special Full Coverage', -25, 0),
    new ExpectedProduct(30, 'Super Sale', -27, 0)
];